typedef int YYSTYPE;

#define	O_AND	1
#define	O_ARRAY	2
#define	O_BEGIN	3
#define	O_CHARACTER	5
#define	O_DO	6
#define	O_ELSE	7
#define	O_END	8
#define	O_FLOAT	9
#define	O_FUNCTION	10
#define	O_IF	11
#define	O_INTEGER	12
#define	O_NOT	13
#define	O_OF	14
#define	O_OR	15
#define	O_PROCEDURE	16
#define	O_PROGRAM	17
#define	O_READ	18
#define	O_THEN	19
#define	O_VAR	20
#define	O_WHILE	21
#define	O_WRITE	22
#define	O_LBRACE	23
#define	O_RBRACE	24
#define	O_CONSTANT	25
#define	O_LE	26
#define	O_LT	27
#define	O_GE	28
#define	O_GT	29
#define	O_EQ	30
#define	O_NE	31
#define	O_ASSIGN	32
#define	O_COLON	33
#define	O_SEMICOLON	34
#define	O_COMMA	35
#define	O_LBRACKET	36
#define	O_RBRACKET	37
#define	O_LPAREN	38
#define	O_RPAREN	39
#define	O_DOTDOT	40
#define	O_PLUS	41
#define	O_TIMES	42
#define	O_IDENTIFER	43
#define	O_MOD	44
#define	O_RETURN	45
#define	O_CHAR	46
#define	O_STRING	47
#define	O_INT	48
#define	O_FLOATCON	49
#define	O_MINUS	50
#define	O_CASE	51


extern YYSTYPE yylval;
